### ISSUE TITLE
Cannot properly open FoxPro db.

### ISSUE THREAD

**Issue by developer88** [hisamu/php-xbase#13]
I have several FoxPro dbs from some accounting software. I need to open it and grab the info.

After my [fix](https://github.com/hisamu/php-xbase/pull/12) i managed to open the file and read some data, but lots of columns (especially with type B, N, F, D) do not received properly - either some corrupted data or just NULL.

Some info about db file from the Table.php:

foxpro: 1
version: 48
encrypted:
mdxFlag:
languageCode:
modifyDate: 1443484800
recordCount: 20426
recordByteLength: 991
inTransaction:
headerLength: 2504
backlist:
encoding: i guess it is 1251, at least data from columns type C is properly encoded.

Is **php-xbase** able to work with this version of FoxPro db?

**Comment by hisamu** [comment]
I'm not sure about specifics for this version. Could you send me a sample table with this version and encoding so I could run some tests?

You can reach me at lsouza@codeinc.com.br

**Comment by gadget00** [comment]
was this ever solved?

**Comment by developer88** [comment]
@gadget00 it was fixed in #15 but i did not have time before to fix comments by @hisamu
