### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by spdionis** [hisamu/php-xbase#17]
Hi, thank you very much for the library, it's going to be very helpful in a project I'm working on now.

I had a quick look at the code and it looks like it will be compatible with php7, which I am using now (that's why I'm using this lib and not the extension).

I will test it out in practice to see if everything works well in practice later.

I suggest changing the php version requirement in composer.json to explicitly note that it supports php7 (after I try it out of course). Leaving the issue here to not forget to notify you if everything runs fine :).

**Comment by hisamu** [comment]
Hi,

That's great, hope to hear about your results soon. If you need any help, just give me a heads up.

Thanks

**Comment by spdionis** [comment]
There is actually an issue: https://github.com/hisamu/php-xbase/pull/18. 

Also docs for writing a '.dbf' file assume that you already have it. At the moment it is **impossible** to create a file as far as i could see because the `WritingTable` parent constructor calls `->open()` on the file, and it complains that it doesn't exist. Commenting that call works fine **for writing**. 

Trivial solution is to override the constructor in WritingTable but that's a BC break. Second solution is add an optional parameter to Table constructor.
