### ISSUE TITLE
Dates seem to have bad encoding

### ISSUE THREAD

**Issue by jpSimkins** [hisamu/php-xbase#2]
It appears that when using a date field, T or D, the encoding makes the data useless. For example, I have a datetime of `2010-03-17 15:56:52` when pulling data from the ODBC connector. When I use this library to import the data into MySQL I noticed all the data fields were `0000-00-00` respectively. So I dumped the data to see what the row looks like before I send it to MySQL and I am getting date results like: `év%'b"`. This appears to only when used from this library and only on date fields. Fetching the data with the ODBC shows the data as expected and so does using it from a DBF viewer. I guess I will have to just use the ODBC driver for my imports :( Was really hoping to use this as it's faster. Hopefully this will help you find the issue. I tried to see if I could convert it back to the original value my changing the encoding myself but no luck there.

**Comment by naderskhan** [comment]
hi. anything done for this? facing same issue when reading from datetime "T".
find sample table here: https://goo.gl/qfyRgf

**Comment by hisamu** [comment]
@naderskhan using your sample table I was able to find a possible bug. Since I don't have other feedback on T columns and this is the only sample I got, I can't assert that's always the case. I will update the code anyway, and if someone else find a bug I hope they will share with us.

**Comment by hisamu** [comment]
Commit ecce006d84b6c569dfb4384dae1e579f2bd22ba8 should fix it.
