### ISSUE TITLE
Upload 0.1.0 stable release to packagist

### ISSUE THREAD

**Issue by root-talis** [hisamu/php-xbase#21]
Right now it is not possible to install "hisamu/php-xbase 0.1.0" via composer because the only available version is "dev-master". Any buggy updates to it will cause dependent software to break, and it is not possible to specify a stable version to protect software from possible bugs and api changes.

**Comment by hisamu** [comment]
Packagist was not updating tag 0.1.0, so I uploaded a new tag.
