### ISSUE TITLE
How i can get a row?

### ISSUE THREAD

**Issue by MarcSky** [hisamu/php-xbase#29]
Hello! In my task i need to get rows how assoc array and analize them! I dont know name column i must to get information from row.
This is realy to get row how assoc array key value and analize this array?

**Comment by nebojsac** [comment]
Just use ```getColumns``` to get the column info, and then ```getRecord``` to get the current row and then use ```getString``` with the column name to get a specific column. 

You can get everything you need with the above and a loop or two.

**Comment by MarcSky** [comment]
@nebojsac it's interesting, I'll try.

**Comment by hisamu** [comment]
Closing the issue since it's more like a question about the lib.
