### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AlexMax** [hisamu/php-xbase#38]
I do not see a license for this library.  Thus, it's not exactly clear what the terms of use are of this library at a glance.

I checked on PHPClasses, and it seems like the original library's license is labeled "Freely Distributable".  It's kind of vague, and it doesn't account for the work you and others have done on the library since then.  Github docs have [this](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) to say about source without a license.

Would it be possible to select a license for this project?  It seems like an MIT license would be in the spirit of that original "Freely Distributable" language, but I'll leave that to your discretion.

**Comment by hisamu** [comment]
I agree with MIT. The reason I didn't include a default license is because the original code didn't actually have a defined one. 

@CDyWeb what do you think about including the MIT license on the project?

**Comment by hisamu** [comment]
@AlexMax I just added the MIT license 👍
