### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by gadget00** [hisamu/php-xbase#44]
Hi; I want to thank you for this amazing code.  It's helping me a LOT.

However, I'm having problems with fields that are of DATE data type.  Somehow instead of getting them in php as "04/31/2017" when I use it (and the actual foxpro DBF table has it saved in this format) I receive "Wednesday, April 31 2017 00:00:01".

How do I set up the date format when receiving the value from the DBF?

Thank you

**Comment by nebojsac** [comment]
I believe it just takes it directly from the DBF data. In PHP you can handle it like this:

```php
<?php
$parsed = date_parse($dateString); //$dateString is the result from php-xbase
$formatted = sprintf('%04d/%02d/%02d', $parsed['day'], $parsed['year'],  $parsed['month']);
```

**Comment by gadget00** [comment]
Hi again!  I figured out that the php-xbase took the actual "date" value from the DBF and transformed in a unix timestamp by default.  What I did is take that default unix stamp and format it as I needed:

`		$unix_time = $record->getDate('fecnacim');
                $nacimiento = date("Y-m-d",$unix_time);
`

**Comment by hisamu** [comment]
👍 👍 👍
