### ISSUE TITLE
Class not found error when try to use XBase lib in PHP

### ISSUE THREAD

**Issue by dzarezenko** [hisamu/php-xbase#5]
I am trying to use https://github.com/hisamu/php-xbase lib in my project.
I have copied XBase folder from repository to the my root and created index.php in my root.

When I try this code:

    <?php
    
    use XBase\Table;
    
    $table = new Table(dirname(__FILE__) . 'data/test.dbf');
    
    while ($record = $table->nextRecord()) {
        echo $record->my_column;
    }
    
    ?>

I received this error:

`Fatal error: Class 'XBase\Table' not found in ...`

What is wrong?

**Comment by hisamu** [comment]
If you're not using **composer** to manage your dependencies, you're probably not autoloading the classes, so you should do a `require()` on all the lib files.

You can also switch into using composer and it's autoloader.
