### ISSUE TITLE
Can't be read single row tables

### ISSUE THREAD

**Issue by efrain-atienza** [hisamu/php-xbase#56]
Tables with single row can't be read with $table->nextRecord()
I think there's an error (table.php line 138) I would change it for:

            if (($this->recordPos + 1) **>** $this->recordCount) {
                return false;
            }

**Comment by gadget00** [comment]
it would be interesting to see your code snippet.  I update a single row table in my code and haven't had any issues loading the record to update it and save it in the DBF so far
